// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfDaDrmoCrxuVZfFtzgD6XA95C4DljNJM',
    appId: '1:488171890330:web:75f45c7675bbcc52d72123',
    messagingSenderId: '488171890330',
    projectId: 'agriloan-de888',
    authDomain: 'agriloan-de888.firebaseapp.com',
    storageBucket: 'agriloan-de888.appspot.com',
    measurementId: 'G-E53CYLCLEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3sAAoSZwz2HwkiF0GLuqtymjkeFDqoY8',
    appId: '1:488171890330:android:a830140152101d36d72123',
    messagingSenderId: '488171890330',
    projectId: 'agriloan-de888',
    storageBucket: 'agriloan-de888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQp9j81I4RXFLxdx_4LUJexCLayacfTrE',
    appId: '1:488171890330:ios:6786283ab736a860d72123',
    messagingSenderId: '488171890330',
    projectId: 'agriloan-de888',
    storageBucket: 'agriloan-de888.appspot.com',
    iosBundleId: 'com.example.loans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQp9j81I4RXFLxdx_4LUJexCLayacfTrE',
    appId: '1:488171890330:ios:8436a1a1a165a293d72123',
    messagingSenderId: '488171890330',
    projectId: 'agriloan-de888',
    storageBucket: 'agriloan-de888.appspot.com',
    iosBundleId: 'com.example.loans.RunnerTests',
  );
}
